spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: SPRING_AI_OPENAI_API_KEY
server:
  tomcat:
    max-http-header-size: 16384